image:
- Visual Studio 2017
- Visual Studio 2015
build: off
test_script:
  - csc -langversion:?
for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  build_script:
  - echo Ubuntu build script
  test_script:
  - echo test script
