image:
- Visual Studio 2017
- Visual Studio 2015
build: off
test_script:
  - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\csc.exe" /langversion:?
for:
-
  matrix:
    only:
      - image: Visual Studio 2015

  build_script:
  - echo Ubuntu build script

