image:
- Visual Studio 2017
- Visual Studio 2015
build: off
test_script:
  - cmd: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\bin\Roslyn\csc.exe /langversion:?
  - dir
for:
-
  matrix:
    only:
      - image: Visual Studio 2015

  build_script:
  - echo Ubuntu build script

