version: '$(app_version).{build}'
image: Visual Studio 2017
init: 
  - cmd: if DEFINED APPVEYOR_PULL_REQUEST_NUMBER (Set build_number=1) ELSE (Set build_number=%APPVEYOR_BUILD_NUMBER%)
  - echo %build_number%
environment:
  app_version: '5.0.0'
  test_var: test_val

for:
-
  branches:
    only:
      - test
      
  environment:
      test_var: overridden

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    package_version: '{version}'
    assembly_version: '$(version)'
    file_version: '{version}'
    informational_version: '{version}'
#init:
  #- ps: Invoke-WebRequest "http://download.microsoft.com/download/B/E/6/BE63E3A5-5D1C-43E7-9875-DFA2B301EC70/adk/adksetup.exe" -OutFile c:\adksetup.exe
  #- ps: Start-Process c:\adksetup.exe -ArgumentList "/quiet" -Wait 
  #- ps: Invoke-WebRequest "https://download.microsoft.com/download/E/F/A/EFA17CF0-7140-4E92-AC0A-D89366EBD79E/adkwinpeaddons/adkwinpesetup.exe" -OutFile c:\adksetup.exe
  #- ps: Start-Process c:\adksetup.exe -ArgumentList "/quiet" -Wait 
#install:
  #- ps: Invoke-WebRequest "http://download.microsoft.com/download/0/1/C/01CC78AA-B53B-4884-B7EA-74F2878AA79F/adk/adksetup.exe" -OutFile c:\adksetup.exe
  #- ps: c:\adksetup.exe /quiet 
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\x86\DISM
  #- cd C:\Program Files (x86)\Windows Kits\8.0\Assessment and Deployment Kit\Deployment Tools\x86\DISM
  #- dir
  #- DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0"
before_build:
  - ps: gci env:*
  - nuget restore
build:
  verbosity: minimal
  
