version: 1.0.{build}
image: Visual Studio 2017

environment:
  test_var: test_val
before_build:
  - ps: gci env:*
  - nuget restore
build_script:
  - echo "custom build script"
  
for:
  -
    branches:
      only: 
        - test
    environment:
      test_var: overridden
