version: '$(app_version).{build}'

image: 
  #- Windows server 2019
  #- Ubuntu
  - Visual Studio 2017

init: 
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #- find ~/ -name *octo*
  #- cmd: if DEFINED APPVEYOR_PULL_REQUEST_NUMBER (Set build_number=1) ELSE (Set build_number=%APPVEYOR_BUILD_NUMBER%)
  - echo %build_number%

  
#install:

#- cmd: IF "%APPVEYOR_REPO_TAG%"=="true" (appveyor PushArtifact appveyor.yml)
 
environment:
  app_version: '5.0.0'
  test_var: test_val

for:

-
  branches:
    only:
      - test

      
  environment:
      test_var: overridden

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '1.2.3.5'
    package_version: '1.2.3.5'
    assembly_version: '1.2.3.5'
    file_version: '1.2.3.5'
    informational_version: '1.2.3.5'
#init:
  #- ps: Invoke-WebRequest "http://download.microsoft.com/download/B/E/6/BE63E3A5-5D1C-43E7-9875-DFA2B301EC70/adk/adksetup.exe" -OutFile c:\adksetup.exe
  #- ps: Start-Process c:\adksetup.exe -ArgumentList "/quiet" -Wait 
  #- ps: Invoke-WebRequest "https://download.microsoft.com/download/E/F/A/EFA17CF0-7140-4E92-AC0A-D89366EBD79E/adkwinpeaddons/adkwinpesetup.exe" -OutFile c:\adksetup.exe
  #- ps: Start-Process c:\adksetup.exe -ArgumentList "/quiet" -Wait 
install:
- ps: >-
    $env:var1 = 'val1'

    $env:var2 = 'val2'

    $vars = @{
      "var1" = $env:var1
      "var2" = $env:var2
    }

    $vars  | ConvertTo-Json | Set-Content .\vars.json
  
 # - find ~/ -name octo
  #- cmd: call C:\Miniconda36-x64\Scripts\activate.bat
  #- cmd: conda update -y -q conda
  #- cmd: conda info --envs
  #- cmd: conda info -a
  #- cmd: python --version
  #- cmd: pip --version
  #- ps: Add-AppveyorMessage "test message"
  #- cmd: echo %configuration%    
  #- ps: Invoke-WebRequest "http://download.microsoft.com/download/0/1/C/01CC78AA-B53B-4884-B7EA-74F2878AA79F/adk/adksetup.exe" -OutFile c:\adksetup.exe
  #- ps: c:\adksetup.exe /quiet 
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\x86\DISM
  #- cd C:\Program Files (x86)\Windows Kits\8.0\Assessment and Deployment Kit\Deployment Tools\x86\DISM
  #- dir
  #- DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0"
before_build:
  #- Start-FileDownload 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.zip?branch=master^&job=Image%3A%20Visual%20Studio%202017'
  - dir C:\*
  - ps: dir C:\OpenSSL-Win64\*
  - ps: gci env:*
  - nuget restore
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build:

  verbosity: minimal
  publish_aspnet_core: true
after_build:
  - 7z a myapp.zip ./before-deploy.ps1 
  #- cd myaspnetwebapp
  #- type myaspnetwebapp.csproj
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
  - path: myapp.zip
    name: my_web_app
  - path: vars.json

