version: 1.0.{build}
image: Visual Studio 2015
environment:
  test_var: test_val
install:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0
before_build:
  - ps: gci env:*
  - nuget restore
build:
  verbosity: minimal
  
for:
  -
    branches:
      only: 
        - test
    environment:
      test_var: overridden
